version: '3'
services:

  #MySQL Service
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql:5.7
    container_name: mysql
    ports: 
        - 3306:3306
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
      MYSQL_ROOT_PASSWORD: 123
    working_dir: /var/www/html
